name: Deploy Agent Service

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and Push
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/agent_service:latest
          docker build -t $IMAGE_NAME ./services/agent_service
          docker push $IMAGE_NAME
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
            IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/agent_service:latest
            docker pull $IMAGE_NAME
            docker stop agent_service || true
            docker rm agent_service || true
            docker run -d --name agent_service \
              --env-file /home/ec2-user/envs/agent_service.env \
              -p 8001:8001 $IMAGE_NAME
