name: CI/CD auth_service

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: create_network # Ensures create_network job completes first
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and Push
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/auth_service:latest
          docker build -t $IMAGE_NAME ./auth_service
          docker push $IMAGE_NAME
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
            IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/auth_service:latest
            docker pull $IMAGE_NAME
            docker stop auth_service || true
            docker rm auth_service || true
            docker run -d --name auth_service \
              --env-file /home/ec2-user/envs/auth_service.env \
              -p 5004:5004 \
              --network mynet \
              $IMAGE_NAME
