name: CI/CD nginx

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and Push
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/ngnix:latest
          docker build -t $IMAGE_NAME ./ngnix
          docker push $IMAGE_NAME
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
            IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/ngnix:latest
            docker pull $IMAGE_NAME
            docker stop ngnix || true
            docker rm ngnix || true
            docker run -d --name ngnix \
              -p 80:80 -p 443:443 \
              -v /etc/letsencrypt:/etc/letsencrypt:ro \
              --network mynet \
              $IMAGE_NAME
